#测试环境
server:
  port: 8082



#连接数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/day7ks?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  main:
    allow-circular-references: true


#mybatis
mybatis:
  #实体类取别名
  type-aliases-package: com.crq.bean
  #扫描mapper
  mapper-locations: classpath:mapper/*Mapper.xml


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false #pageSize=0
